#!/usr/bin/env ruby

lib = File.expand_path("../lib", __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

require "rpn_expression"

@rpn = RPNExpression.new

loop do
  print "rpn> "
  input = gets.chomp

  case input
  when "exit"
    puts "Bye bye!"
    exit
  else
    begin
      puts @rpn.evaluate(input)
    rescue StandardError
      puts "Error evaluating RPN expression: #{input.inspect}"
    end
  end
end
